### ISSUE TITLE
Digits out of order  (4 digit display)

### ISSUE THREAD

**Issue by diegostf** [RobTillaart/TM1637_RT#15] opened 2022-04-12 12:01 UTC
I'm testing this lib on platformio + VS code, using STM32F.

The code below should show 1234 on the display, but it shows the digits "1  4". Center digits do not appear

```cpp
#include <TM1637.h>

TM1637 display;

const uint8_t CLK_PIN = PC13;
const uint8_t DTA_PIN = PC14;


void StartDisplay(void)
{
    display.init(CLK_PIN, DTA_PIN, 4);       // Clock pin, data pin, number digits
    display.displayClear();

    long aux = 1234;
    display.displayInt(aux);
}
```

Changing the code, the display shows: "3216". My display only has 4 digits.

```cpp
#include <TM1637.h>

TM1637 display;

const uint8_t CLK_PIN = PC13;
const uint8_t DTA_PIN = PC14;


void StartDisplay(void)
{
    display.init(CLK_PIN, DTA_PIN, 6);       // Clock pin, data pin, number digits
    display.displayClear();

    long aux = 123456;
    display.displayInt(aux);
}
```

**Comment by RobTillaart** [comment] 2022-04-12 12:18
(updated your post)

I'm ill at the moment so it might take some weeks before I can dive into this issue. So a quick remark:

Never tested the library with **STM32F**, your fix is interesting as it might point to a cause (layout of memory ?).

Do you get the same/similar problems with float?  e.g. TM.displayFloat(3.456);

**Comment by diegostf** [comment] 2022-04-12 12:24
> (updated your post)
> 
> I'm ill at the moment so it might take some weeks before I can dive into this issue. So a quick remark:
> 
> Never tested the library with **STM32F**, your fix is interesting as it might point to a cause (layout of memory ?).
> 
> Do you get the same/similar problems with float? e.g. TM.displayFloat(3.456);

Take your time. I hope you get well.

Yes, with float the same problem happens.

**Comment by RobTillaart** [comment] 2022-04-12 12:28
The problem is in 
```cpp
void TM1637::displayRaw(uint8_t * data, uint8_t pointPos)
```

As it seems hardcoded for 6 digits display (Only one tested so far).
Do you have a link to the datasheet of the 4 digit display?

So I think you should add your patch there, like this.
```cpp
void TM1637::displayRaw(uint8_t * data, uint8_t pointPos)
{
  if (_digits == 4)
  {
    data[5] = data[1]; 
    data[4] = data[2]; 
  }
  ...
```
Then it might work for float too (please verify)

**Comment by diegostf** [comment] 2022-04-12 12:39
I tested it and it worked fine. Although in displayFloat(float value) there is some rounding down (3.145 is shown as "3144").

**Comment by diegostf** [comment] 2022-04-12 12:43
Another question: why do you send bytes 3, 4 and 5 and then 0, 1, 2, in  `void TM1637::displayRaw(uint8_t * data, uint8_t pointPos)` ?

**Comment by RobTillaart** [comment] 2022-04-12 13:46
I will add such a 4 digit display next time I order hardware.

**Comment by diegostf** [comment] 2022-04-12 16:02
> I will add such a 4 digit display next time I order hardware.

Now, it works fine, for this display.

`void TM1637::displayRaw(uint8_t * data, uint8_t pointPos)
{
  uint8_t b, dp;
  start();
  writeByte(TM1637_ADDR_AUTO);
  stop();

  start();
  writeByte(TM1637_CMD_SET_ADDR);


  for(uint8_t i = _digits - 1; i < 250; i--) // need overflow, to break out
  {
    dp = data[i] & 0x80;
    data[i] &= 0x7f;
    if(data[i] <= 17) {
      b = seg[data[i]];
    }
    else if(data[i] <= 37) {
      b = alpha_seg[data[i]-18];
    }
    if (i == pointPos || dp) b |= 0x80;
    writeByte(b);
  }

  stop();

  start();
  writeByte(TM1637_CMD_DISPLAY | _brightness);
  stop();
}`

**Comment by RobTillaart** [comment] 2022-04-12 17:09
Thanks for this code, it is pretty straightforward, If i understand correctly you write the bytes  in order 3, 2, 1, 0.

I leave this issue open until I have time (and a display) to test and mix/merge the code.

**Comment by diegostf** [comment] 2022-04-13 01:27
> Thanks for this code, it is pretty straightforward, If i understand correctly you write the bytes in order 3, 2, 1, 0.

Yes, you're right.
This is the layout of the display I use.

![Tm1637](https://user-images.githubusercontent.com/7763609/163080675-1775781e-fcdb-407c-83d0-76d977b5de0d.png)

**Comment by RobTillaart** [comment] 2022-04-14 15:10
FYI, I ordered a 4 segment display, so if all goes well next week I can start testing.

**Comment by diegostf** [comment] 2022-04-14 15:42
> FYI, I ordered a 4 segment display, so if all goes well next week I can start testing.

Thanks a lot!

**Comment by RobTillaart** [comment] 2022-04-16 19:52
@diegostf 
The 4 segment "clock" display is in and I have a working version. 
There is redundancy in the code in **displayRaw()** that I want to refactor.
The ":" of the clock is the decimal point of digit 1

to be continued (after Easter)

**Comment by RobTillaart** [comment] 2022-04-17 08:55
@diegostf 
Created a develop branch in which the 4 digit display is supported. Just use 4 as last parameter in **init()**.

**displayRaw()** has been refactored to use a **digitOrder[]** array. This array can be filled wit **setDIgitOrder()** by the user to adjust non-supported displays. Currently this array has 8 elements to support displays up to 8 digits.

Please verify if the library now works for you.  (note a small example has been added too).

**Comment by diegostf** [comment] 2022-04-17 23:29
> @diegostf Created a develop branch in which the 4 digit display is supported. Just use 4 as last parameter in **init()**.
> 
> **displayRaw()** has been refactored to use a **digitOrder[]** array. This array can be filled wit **setDIgitOrder()** by the user to adjust non-supported displays. Currently this array has 8 elements to support displays up to 8 digits.
> 
> Please verify if the library now works for you. (note a small example has been added too).

@RobTillaart did you update this repository? I didn't find new code.

**Comment by RobTillaart** [comment] 2022-04-18 01:12
https://github.com/RobTillaart/TM1637_RT/tree/develop

**Closed** 2022-04-21 14:31 UTC
Labels: bug, question

**Comment by RobTillaart** [comment] 2022-04-21 14:32
@diegostf 
Merged the new version into master,
if there are still (or new) related problems feel free to reopen the issue.
